<?php
/**
 * Tests for inc-release-notes.php.
 *
 * @package ForceRefresh
 */

namespace JordanLeven\Plugins\ForceRefresh;

use PHPUnit\Framework\TestCase;

require_once __DIR__ . '/../../../includes/actions/admin/inc-release-notes.php';

/**
 * README fixture with leading whitespace on date and section-header lines,
 * matching the format generated by createWordPressReadMe.js.
 */
const README_FIXTURE = <<<'README'
Plugin header content
== Changelog ==
#### 1984.1.24
 _Released on January 24, 1984_

 ##### **Bug Fixes**
* Restore ramda to plugin dependencies.

#### 2007.6.29
 _Released on June 29, 2007_

 ##### **New Features**
* Update minimum PHP version to 8.2.
README;

/**
 * Tests for the release notes parser.
 */
final class ReleaseNotesTest extends TestCase {

    /**
     * Parse a README fixture string into the structured notes array.
     *
     * Replicates the loop inside get_release_notes_json without going
     * through the filesystem, so the two version use cases can be tested
     * in isolation.
     *
     * @param string $plugin_version The simulated installed plugin version.
     * @return array The parsed notes array.
     */
    private function parseReadme( string $plugin_version ): array {
        $release_notes         = get_release_notes_from_plugin_readme( README_FIXTURE );
        $notes_formatted       = array();
        $current_version_index = null;

        foreach ( $release_notes as $note ) {
            assign_release_note_based_on_role( $plugin_version, $current_version_index, $notes_formatted, $note );
        }

        return $notes_formatted;
    }

    /**
     * Test that a stable plugin version is marked as the current version.
     */
    public function testStableVersionIsMarkedAsCurrent() {
        $result = $this->parseReadme( '1984.1.24' );

        $this->assertTrue( $result['1984.1.24']['isCurrentVersion'] );
    }

    /**
     * Test that other versions are not marked as current when on a stable release.
     */
    public function testOtherVersionsAreNotMarkedAsCurrentOnStableRelease() {
        $result = $this->parseReadme( '1984.1.24' );

        $this->assertFalse( $result['2007.6.29']['isCurrentVersion'] );
    }

    /**
     * Test that a stable release correctly parses the release date despite leading whitespace.
     */
    public function testStableVersionParsesDateCorrectly() {
        $result = $this->parseReadme( '1984.1.24' );

        $this->assertEquals( 'Released on January 24, 1984', $result['1984.1.24']['date'] );
    }

    /**
     * Test that a stable release correctly parses section notes.
     */
    public function testStableVersionParsesNotesCorrectly() {
        $result = $this->parseReadme( '1984.1.24' );

        $this->assertEquals( 'Restore ramda to plugin dependencies.', $result['1984.1.24']['notes'][0]['sectionNotes'][0] );
    }

    /**
     * Test that a beta plugin version does not crash the parser.
     */
    public function testBetaVersionDoesNotThrow() {
        $this->expectNotToPerformAssertions();
        $this->parseReadme( '1984.1.24-9EB32F.1' );
    }

    /**
     * Test that no version is marked as current when the installed version is a beta.
     */
    public function testBetaVersionHasNoCurrentVersion() {
        $result = $this->parseReadme( '1984.1.24-9EB32F.1' );

        foreach ( $result as $version => $data ) {
            $this->assertFalse( $data['isCurrentVersion'], "Version {$version} should not be marked current for a beta install." );
        }
    }

    /**
     * Test that the beta version still parses all changelog entries correctly.
     */
    public function testBetaVersionParsesAllVersions() {
        $result = $this->parseReadme( '1984.1.24-9EB32F.1' );

        $this->assertArrayHasKey( '1984.1.24', $result );
        $this->assertArrayHasKey( '2007.6.29', $result );
    }
}
