version: '3.4'
services:
  db:
    container_name: 'force-refresh-db-dev-container'
    image: 'mysql:5.7'
    volumes:
      - './.docker-build/data/mysql:/var/lib/mysql'
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 18766:3306
    environment:
      MYSQL_ROOT_PASSWORD: force-refresh_root_password
      MYSQL_DATABASE: force-refresh-dev-db
      MYSQL_USER: force-refresh-dev-user
      MYSQL_PASSWORD: force-refresh-dev-password
  wordpress:
    container_name: 'force-refresh-dev-container'
    depends_on:
      - db
    image: 'wordpress:5.2'
    ports:
      - '80:80'
    environment:
      WORDPRESS_DB_HOST: 'db:3306'
      WORDPRESS_DB_NAME: force-refresh-dev-db
      WORDPRESS_DB_USER: force-refresh-dev-user
      WORDPRESS_DB_PASSWORD: force-refresh-dev-password
    volumes:
      - "./.docker-build/wordpress:/var/www/html"
      - "./:/var/www/html/wp-content/plugins/force-refresh"
