export default (localizedData) => ({
  featureFlags: localizedData.featureFlags ?? {},
  settings: {
    customRefreshIntervalMaximumInMinutes: localizedData.refreshOptions.customRefreshIntervalMaximumInMinutes,
    customRefreshIntervalMinimumInMinutes: localizedData.refreshOptions.customRefreshIntervalMinimumInMinutes,
    isDebugActive: localizedData.isDebugActive,
    refreshFromAdminBar: localizedData.refreshOptions.showRefreshInMenuBar,
    refreshInterval: localizedData.refreshOptions.refreshInterval,
  },
  site: {
    isMultiSite: localizedData.isMultiSite,
    scheduledRefreshes: localizedData.scheduledRefreshes,
    siteId: localizedData.siteId,
    siteName: localizedData.siteName,
    siteUrl: localizedData.siteUrl,
    versionForceRefreshInstalled: localizedData.versions.forceRefresh.version,
    versionForceRefreshRequired: localizedData.versions.forceRefresh.versionRequired,
    versionPhpEolDate: localizedData.versions.php.eolDate ?? null,
    versionPhpInstalled: localizedData.versions.php.version,
    versionPhpRequired: localizedData.versions.php.versionRequired,
    versionWordPressEolDate: localizedData.versions.wordPress.eolDate ?? null,
    versionWordPressInstalled: localizedData.versions.wordPress.version,
    versionWordPressRequired: localizedData.versions.wordPress.versionRequired,
  },
});
