name: Release
on:
  push:
    tags:
    - "*"
jobs:
  tag:
    name: Deploy to WordPress.org
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build the plugin
      run: |
        composer install
        composer lint
        npm install
        npm run lint
        npm run build
        npm run createWpReadme
        npm prune --production
        composer install --no-dev --no-scripts
    - name: Deploy plugin to WordPress.org
      uses: 10up/action-wordpress-plugin-deploy@stable
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: force-refresh
