name: Release Production Build
on:
  push:
    branches: [ master, release--* ]
  pull_request:
    branches: [ master,  release--* ]

jobs:
  deploy:
    name: Release Production Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4

    - name: Install node dependencies
      run: npm ci

    - name: Install composer dependencies
      run: composer install

    - name: Lint JavaScript source code
      run: npm run lint

    - name: Lint PHP source code
      run: composer lint

    - name: Test JavaScript source code
      run: npm test

    - name: Build JavaScript artifact
      run: npm run build:beta

    - name: Build PHP artifact
      run: composer build ./ ./Force-Refresh-${{ steps.package-version.outputs.current-version}}.zip

    - name: Create release notes
      run: npm run createWpReadme

    - name: Prune JavaScript dependencies
      run: npm prune --production


    - name: Prune PHP dependencies
      run: composer install --no-dev --no-scripts

    # - name: Deploy plugin to WordPress.org
    #   uses: 10up/action-wordpress-plugin-deploy@stable
    #   env:
    #     SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
    #     SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
    #     SLUG: force-refresh

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: ./Force-Refresh-${{ steps.package-version.outputs.current-version}}.zip
        asset_name: Force_Refresh_v${{ steps.package-version.outputs.current-version}}.zip
        tag_name: ${{ github.ref }}
        release_name: Force Refresh ${{ github.ref }}
        draft: false
        prerelease: false
