name: Release Production Build
on:
  push:
    tags:
      - "v[0-9].[0-9].[0-9](?!-[0-9])"

jobs:
  deploy:
    name: Release Production Build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: |
        npm install
        composer install

    - name: Lint
      run: |
        composer lint
        npm run lint

    - name: Test
      run: composer test

    - name: Build the plugin
      run: npm run build

    - name: Create release notes
      run: npm run createWpReadme

    - name: Prune dependencies
      run: |
        npm prune --production
        composer install --no-dev --no-scripts

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Force Refresh ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Deploy plugin to WordPress.org
      uses: 10up/action-wordpress-plugin-deploy@stable
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: force-refresh
