name: Release Beta Build
on:
  pull_request:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-*.[0-9]+"
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-*.[0-9]+"

jobs:
  build:
    name: Release Beta Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Get Release Number
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master

    - name: Install node dependencies
      run: npm ci

    - name: Install composer dependencies
      run: composer install

    - name: Lint JavaScript source code
      run: npm run lint

    - name: Lint PHP source code
      run: composer lint

    - name: Test JavaScript source code
      run: npm test

    - name: Create release notes
      run: npm run createWpReadme

    - name: Build JavaScript artifact
      run: npm run build

    - name: Build PHP artifact
      run: composer build ./ ./Force-Refresh-${{ steps.package-version.outputs.current-version}}.zip

    - name: Get commits since last release
      id: changes
      uses: simbo/changes-between-tags-action@v1
      with:
        validate-tag: false
        tag-pattern: '^v[0-9]+\.[0-9]+\.[0-9]+-.*\.[0-9]+$'
        include-tag-commit: false

    - name: Create GitHub release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./Force-Refresh-${{ steps.package-version.outputs.current-version}}.zip
        asset_name: Force_Refresh_v${{ steps.package-version.outputs.current-version}}.zip
        tag: ${{ github.ref }}
        release_name: Force Refresh ${{ steps.package-version.outputs.current-version }}
        overwrite: true
        prerelease: true
        body: "This is a beta release of Force Refresh (v${{ steps.package-version.outputs.current-version}}). This release is intended to be used for debugging and **should not** be used on production sites unless directed. Production-stable versions are available at https://wordpress.org/plugins/force-refresh. \n\n## Changelog Since Last Release\n\n${{ steps.changes.outputs.changes || 'Performance enhancements and bug fixes' }}"
